### PR TITLE
switch from ctdk/goas/v2/logger to tideland/goas/logger

### PR DESCRIPTION
**Pull request by theckman**
The tideland/goas repo is now gone, and some of the code within `ctdk/goas` refers to it. In this PR I propose goiardi switches to the new `tideland/golib` repo.

I believe the library is mostly compatible with the changes you made to `goas/v2/logger`:

* https://github.com/tideland/golib/blob/master/logger/nosyslogger.go

Apologies for all of the import changes involved, `goimports` automatically cleaned them up.

### CODE REVIEW

**Comment by theckman** [comment]
I'm working on a project that depends on `goiardi` and this is causing me to be unable to build the project in a CI/CD system because the `go get` for `tideland/goas` fails.

**Comment by ctdk** [comment]
I just need to check over that and make sure it's as compatible as I need - the fix may end up being to update my fork of that goas logger, because the reason I forked it in the first place was to add syslogging.

**Comment by theckman** [comment]
Oh, I took a look at the commit on your fork and my understanding was that you just made it compatible with Windows/Plan9 by building a specific file (with a dummy syslog) for Windows and P9 only. The golib logger seems to have done the same.

Apologies of I am misunderstanding the changes.

**Comment by ctdk** [comment]
Oh, maybe that's what the change was. It's been a while since I did that. Taking a look now; I've been wrapped up in some other stuff for a bit.

**Comment by ctdk** [comment]
Wow, you know what I did better than I did. I'll pull this in and test it out now, but so far I don't see any problems.

**Comment by ctdk** [comment]
I had to massage it a little more - you missed the forked logging library a couple of places, and the logging levels needed massaging slightly to accommodate the new "Fatal" log level, and while I was at it I changed some Criticalf statements to Fatalf.

It's been merged into the proxy-opts branch, which is where I'm building the next release. It should be ready soon, but I need to update some docs first.

**Comment by theckman** [comment]
Weird. I did a find and replace across the entire repo, so I figured I got them all. I guess that's what I get for not confirming my work. Sorry about that.

Sounds good. Thank you for taking the time to look in to this. I'll keep an eye out for that branch making its way in to master.

**Comment by ctdk** [comment]
I only noticed the log level bit because it was wasn't printing out any debug statements, only INFO and above. If you weren't looking for that specific thing you wouldn't realize the levels were off by one is all.

It should be turned around pretty soon. I was going to work on it this weekend, but got tied up working on cleaning my garage and whatnot.

**Pull request merged**
